// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/introspection run DDL, which is unreliable through a pooled
    // (PgBouncer) connection. Prefer a direct connection via DIRECT_URL, falling
    // back to DATABASE_URL for local dev. The runtime client (src/lib/db.ts) still
    // uses the pooled DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
